1.From 某個套件 import

In [1]:
arr = array([1,3,4])

NameError: name 'array' is not defined

In [2]:
from numpy import * #import所有numpy裏頭指令

In [3]:
arr = array([1,3,4])
arr

array([1, 3, 4])

In [4]:
from numpy import array #從numpy 單獨 import array 

In [5]:
arr = array([1,3,-4])

In [6]:
arr

array([ 1,  3, -4])

2.import 套件

In [7]:
import numpy #利用某套件.

In [8]:
numpy.sin(1)

0.8414709848078965

In [9]:
numpy.pi

3.141592653589793

In [10]:
arr = numpy.array([1,3,-4])

In [11]:
arr

array([ 1,  3, -4])

3. import套件as

In [12]:
import numpy as np

In [13]:
np.sin(1)

0.8414709848078965

In [14]:
np.pi

3.141592653589793

In [15]:
arr = np.array([1,3,-4])

In [16]:
arr

array([ 1,  3, -4])

In [17]:
np.random.randint(1,5)

4

In [19]:
import random as rnd

In [22]:
[np.random.randint(1,5) for i in range(10)] #numpy的random沒有包括5

[3, 2, 2, 1, 4, 1, 3, 3, 4, 4]

In [23]:
[rnd.randint(1,5) for i in range(10)] #random的randint有包括5

[4, 4, 2, 5, 2, 2, 2, 2, 2, 4]

In [3]:
from numpy import array
x = array([2,3,10,5])

In [5]:
x**2 + 2*x

array([  8,  15, 120,  35])